version: '3'

services:
  mysql_master:
    image: mysql:8.0.12
    container_name: mysql_master
    environment:
      - MYSQL_ROOT_PASSWORD=root
    # ports:
    #   - 3306:3306
    volumes:
      # - ./data/mysql-master:/var/lib/mysql/
      - ./config/mysql-master:/etc/mysql/conf.d/
    restart: always

  mysql_replica:
    image: mysql:8.0.12
    container_name: mysql_replica
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      # - ./data/mysql-replica:/var/lib/mysql/
      - ./config/mysql-master-replica:/etc/mysql/conf.d/
    restart: always

  # mysql_replica_2:
  #   image: mysql:8.0.12
  #   container_name: mysql_replica_2
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=root
  #   volumes:
  #     # - ./data/mysql-replica:/var/lib/mysql/
  #     - ./config/mysql-replica:/etc/mysql/conf.d/
  #   restart: always

  mysql_configure:
    image: mysql:8.0.12
    container_name: mysql_configure
    env_file:
      - ./.env
    environment:
      - MYSQL_DEV=test
    volumes:
      - ./mysql_connector.sh:/tmp/mysql_connector.sh
      - ./test.sql:/tmp/test.sql
    command: /bin/bash -x /tmp/mysql_connector.sh
